version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  model-init:
    image: curlimages/curl
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
      echo 'Waiting for Ollama to be ready...' &&
      until curl -s http://ollama:11434/api/tags; do sleep 1; done &&
      echo 'Pulling deepseek-llm:7b-chat...' &&
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"deepseek-llm:7b-chat\"}' &&
      echo 'Model pulled successfully.'
      "
    restart: "no"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your_random_secret_key
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  ollama_data:
  qdrant_storage:
